name = "SHTOOLS"
uuid = "c916fbc8-b869-4f3a-86b1-58538899335e"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "1.4.0"

[deps]
SHTOOLS_jll = "ff580fc6-ede1-5b7e-942f-684e38381daf"

[compat]
SHTOOLS_jll = "4.10.4"
julia = "1.6"
